default_language_version:
  python: python3

ci:
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit suggestions"
  autoupdate_schedule: quarterly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: requirements-txt-fixer

  - repo: local
    hooks:
      - id: lint-misc
        name: lint misc
        entry: bash -c "date -u +%Y-%m-%dT%H:%M:%SZ > /tmp/lint_marker && echo lint ok"
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.7
    hooks:
      - id: ruff-check
        args: [ --fix ]

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.2
    hooks:
      - id: autoflake
        args: [--remove-all-unused-imports, --in-place]

